### PR TITLE
Owner creates issue

### PR DESCRIPTION
**Pull request by draistis**
Pretty much copy-paste of faults, with some QOL that bothered me

Solves task: PVP-40.

### CODE REVIEW

**Review by Karolinskis — CHANGES_REQUESTED** [review]
There's currently no way for the owner to create the issue withouth writting it in the URL, add some button so it would be easier.

**Comment by Karolinskis** [comment]
Don't forget to fix the branch conflicts as well.

**Comment by draistis** [comment]
Should be fixed @Karolinskis

**Review by Karolinskis — CHANGES_REQUESTED** [review]
image
The button has no styling fix this, it's pretty hard to know for the user if this is actryally a button

**Comment by draistis** [comment]
Forgot bg is white

**Comment by Karolinskis** [comment]
Don't forget to re-request a review, because I don't get an notification otherwise.

**Review by Karolinskis — APPROVED** [review]
LGTM

**Pull request merged**
